# my-python-examples task-unit-tests.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: my-python-examples

outputs:
- name: coverage-results

run:
  path: ./my-python-examples/ci/scripts/unit-tests.sh
